name: Stage PR workflow

on:
  pull_request:
    branches:
      - stage
jobs:
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      json: ${{ steps.changes.outputs.json }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout PR repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout stage repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 'main'
          path: 'stage-branch'
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=json::$(git diff  --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .json$ | xargs)"
  lint:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    if: ${{needs.changedfiles.outputs.json}}
    steps:
      - name: echo changed files
        run: echo ${{needs.changedfiles.outputs.json}}   
