name: Stage PR workflow

on:
  pull_request:
    branches:
      - stage
jobs:
  hello_world_job:
      runs-on: ubuntu-latest
      name: A job to say hello
      steps:
        # To use this repository's private action,
        # you must check out the repository
        - name: Checkout repo
          uses: actions/checkout@v2
        - name: Hello world action step
          uses: ./ # Uses an action in the root directory
          id: hello
          with:
            who-to-greet: 'Mona the user'
        # Use the output from the `hello` step
        - name: Get the output time
          run: echo "The time was ${{ steps.hello.outputs.time }}"
  changedfiles:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      all: ${{ steps.changes.outputs.all}}
      json: ${{ steps.changes.outputs.json }}
    steps:
        # Make sure we have some code to diff.
      - name: Checkout PR repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout stage repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: 'stage'
          path: 'stage-branch'
      - name: Get changed files
        id: changes
        # Set outputs using the command.
        run: |
          echo "::set-output name=all::$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | xargs)"
          echo "::set-output name=json::$(git diff  --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep .json$ | xargs)"
  lint:
    runs-on: ubuntu-latest
    # require the first job to have ran
    needs: changedfiles
    # only run there are changed files
    if: ${{needs.changedfiles.outputs.json}}
    steps:
      - name: echo changed files
        run: echo ${{needs.changedfiles.outputs.json}}   
